package org.tuanit.view;


import com.intellij.uiDesigner.core.GridLayoutManager;
import lombok.SneakyThrows;
import org.springframework.stereotype.Component;

import javax.swing.*;
import java.awt.*;
import java.awt.geom.RoundRectangle2D;
import java.io.IOException;
import java.util.concurrent.CompletableFuture;

@Component
public class LoadingView extends JFrame {
    private JPanel panel1;

    public LoadingView() throws IOException {
        //setAlwaysOnTop(true);
        getContentPane().setBackground(Color.WHITE);
        setResizable(false);
        setSize(200, 70);
        setLocationRelativeTo(null);
        setUndecorated(true);
        //setBackground(new Color(0, 0, 0, 180));
        setShape(new RoundRectangle2D.Double(10, 10, 180, 50, 20, 20));
        ImageIcon loading = new ImageIcon(getClass().getResource("/loading.gif"));
        add(new JLabel(loading, JLabel.CENTER));

        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //setIconImage(ImageIO.read(getClass().getResource(UrlConstant.URL_ENUM.getIcon())));
    }

    public LoadingView(JProgressBar progressBar) {
        setTitle("Xin chờ ...");
        setResizable(false);
        setSize(260, 100);
        setLocationRelativeTo(null);
        add(progressBar);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //try {
        //setIconImage(ImageIO.read(getClass().getResource(UrlConstant.URL_ENUM.getIcon())));
        //} catch (IOException ignored) {
        //}
    }

    public <T> void loading(JFrame jFrame, CompletableFuture<T> tCompletableFuture) {
        loading();
        if (jFrame != null)
            jFrame.setVisible(false);
        tCompletableFuture.whenComplete((t, e) -> {
            setVisible(false);
            if (jFrame != null)
                SwingUtilities.invokeLater(() -> {
                    jFrame.setVisible(true);
                });
        });
    }

    public <T> void loading(JFrame jFrame, Runnable runnable) {
        loading();
        if (jFrame != null)
            jFrame.setVisible(false);
        runnable.run();
        setVisible(false);
        if (jFrame != null)
            jFrame.setVisible(true);
    }

    @SneakyThrows
    private void loading() {
        setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    //private JPanel loadingPanel() {
    //    JPanel panel = new JPanel();
    //    BoxLayout layoutMgr = new BoxLayout(panel, BoxLayout.PAGE_AXIS);
    //    panel.setLayout(layoutMgr);
    //    JLabel jlabelLoad = new JLabel();
    //    jlabelLoad.setHorizontalAlignment(SwingConstants.CENTER);
    //    JLabel jlabelText = new JLabel("Xin chờ ...", SwingConstants.CENTER);
    //    ImageIcon imageIcon = new ImageIcon(getClass().getResource("/load.gif"));
    //    jlabelLoad.setIcon(imageIcon);
    //    imageIcon.setImageObserver(jlabelLoad);
    //    //jlabelLoad.setHorizontalAlignment(JLabel.CENTER);
    //
    //    panel.add(jlabelLoad);
    //    panel.add(jlabelText);
    //    return panel;
    //}
}
