name: Mail Spammer.

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          java-package: 'jdk'
          cache: maven
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "{version}"
          replace: ${{ github.run_number }}
          include: "src/main/java/**"
      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: restore
      - name: Build with Maven
        run: mvn clean package
      - name: Save Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: save
      #      - name: run Obfuscate
      #        run: |
      #          java -jar Skidfuscator.jar obfuscate ${{ github.workspace }}/target/social-tools-1.0.jar -li=${{ github.workspace }}/target/libs -o='${{ github.workspace }}/target/zalo-tools.jar'
      - name: run Obfuscate
        run: |
          java -jar obfuscator-1.9.3.jar --jarIn ${{ github.workspace }}/target/mailtools-1.0.jar --jarOut ${{ github.workspace }}/target/gmail-tools.jar
      - name: Run headless test
        uses: coactions/setup-xvfb@v1
        timeout-minutes: 1
        with:
          run: 'java -jar ${{ github.workspace }}/target/gmail-tools.jar heath'
      #      - name: Create zip jar only
      #        run: |
      #          cd ${{ github.workspace }}/target
      #          zip -r gmail-tool-jar-only.zip zalo-tools.jar
      #      - name: Upload only jar to Google Drive
      #        uses: adityak74/google-drive-upload-git-action@v0.3
      #        with:
      #          credentials: ${{ secrets.GG_DRIVER_SECRET }}
      #          filename: ${{ github.workspace }}/target/zalo-tool-jar-only.zip
      #          overwrite: true
      #          folderId: '1wsSruIeFFbGeqtohVLbTHP_eWpRCVDLb' # Replace with your Google Drive folder ID
      #      - name: Create zip file and library
      #        run: |
      #          cd ${{ github.workspace }}/target
      #          zip -r social-tool.zip ${{ github.workspace }}/zalo-tools.bat libs zalo-tools.jar
      #      - name: Upload jar libs to Google Drive
      #        uses: adityak74/google-drive-upload-git-action@v0.3
      #        with:
      #          credentials: ${{ secrets.GG_DRIVER_SECRET }}
      #          filename: ${{ github.workspace }}/target/social-tool.zip
      #          overwrite: true
      #          folderId: '1wsSruIeFFbGeqtohVLbTHP_eWpRCVDLb' # Replace with your Google Drive folder ID


      - name: Acquire Google access token
        id: google-access-token
        uses: playeveryware/action-google-access-token@v1
        with:
          credentials: ${{ secrets.SERVICE_ACCOUNT_KEY_JSON }}
          scope: 'https://www.googleapis.com/auth/drive.readonly'
      - name: Download file
        if: steps.cache.outputs.cache-hit != 'true'
        uses: playeveryware/action-google-drive-download@v1
        with:
          token: ${{ steps.google-access-token.outputs.token }}
          file-id: 1yWs9I6Q8rPXQDRtbgOYe1wYrzX5X78hW
          path: "jdk.zip"
      - name: create exe file
        run: |
          ls
          chmod 755 ${{ github.workspace }}/launch4j/bin/ld
          chmod 755 ${{ github.workspace }}/launch4j/bin/windres
          unzip jdk.zip -d ${{ github.workspace }}/target
          sudo java -jar ${{ github.workspace }}/launch4j/launch4j.jar test.xml
          cd ${{ github.workspace }}/target
          ls
          zip -r social-tool.zip libs gmail-tools.jar gmail-tools.exe jdk
      - name: Upload jar libs exe to Google Drive
        uses: adityak74/google-drive-upload-git-action@v0.3
        with:
          credentials: ${{ secrets.GG_DRIVER_SECRET }}
          filename: ${{ github.workspace }}/target/social-tool.zip
          overwrite: true
          folderId: '15T7ZALBZoXwIX9Gs2fF4RPX2y1TgAGq6' # Replace with your Google Drive folder ID
      - name: Create zip jar only
        run: |
          cd ${{ github.workspace }}/target
          zip -r gmail-tool-jar-only.zip gmail-tools.jar gmail-tools.exe
      - name: Upload only jar to Google Drive
        uses: adityak74/google-drive-upload-git-action@v0.3
        with:
          credentials: ${{ secrets.GG_DRIVER_SECRET }}
          filename: ${{ github.workspace }}/target/gmail-tool-jar-only.zip
          overwrite: true
          folderId: '15T7ZALBZoXwIX9Gs2fF4RPX2y1TgAGq6' # Replace with your Google Drive folder ID
      ####
      - name: List files in libs folder
        id: list_files
        run: echo "::set-output name=files::$(ls ${{ github.workspace }}/target/libs | tr '\n' ',')"
      - name: checkout branch logging
        uses: actions/checkout@master
        with:
          repository: minhtuan9x/socialstoollog
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Log ls
        run: ls
      - name: Find and Replace library
        run: |
          echo "${{ steps.list_files.outputs.files }}" > gmail/library.txt
      - name: Find and Replace log
        run: |
          echo "3.${{ github.run_number }}" > gmail/version.txt
      - name: Replace commit message
        run: |
          echo "Nội Dung cập nhật: ${{ github.event.head_commit.message }}" > gmail/commit.txt
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          repository: minhtuan9x/socialstoollog
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          branch: main
